apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: private-gitlab-cicd
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/gbenhaim-apps/user1-tenant/private-gitlab-cicd/private-gitlab-cicd@sha256:15f3338a2ff72f13f938a2720f0ea7318bf3190f1931694c6ce3ba452323b4eb
        name: container-image
        resources: {}
status: {}
