apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: private-gitlab-cicd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: private-gitlab-cicd
    app.kubernetes.io/part-of: private-gitlab-cicd
  name: private-gitlab-cicd
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: private-gitlab-cicd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: private-gitlab-cicd
    spec:
      containers:
      - image: quay.io/gbenhaim-apps/user1-tenant/private-gitlab-cicd/private-gitlab-cicd@sha256:6159224e93fd57c4e1861b41659c3b26be889378cc197612af8837952a887cb7
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
